-- ============================
-- CREATE TABLE: CUSTOMER
-- ============================
CREATE TABLE CUSTOMERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255)
   
);





-- ============================
-- INSERT DATA FOR CUSTOMER
-- ============================
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (1, 'rahul');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (2, 'bhushan');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (3, 'Amit Kumar');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (4, 'Priya Sharma');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (5, 'Ravi Patel');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (6, 'Ananya Gupta');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (7, 'Vikram Singh');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (8, 'Neha Verma');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (9, 'Sandeep Yadav');
INSERT INTO CUSTOMERS (ID, CUSTOMER_NAME) 
VALUES (10, 'Radhika Iyer');
ALTER TABLE CUSTOMERS ALTER COLUMN ID RESTART WITH 11;

